---
# defaults file for zabbix
#
- name: Update
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: Install EPEL release
  yum:
    name: epel-release
    state: present

- name: Install
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - httpd
    - php
    - php-mysql
    - php-ldap
    - php-bcmath-
    - php-mbstring

