---
# Tasks specific for RedHat systems

- name: "RedHat | Use Zabbix package name"
  set_fact:
    zabbix_server_package: "zabbix-server-{{ zabbix_server_database }}"
  when:
    - zabbix_repo == "zabbix" or zabbix_repo == "other"
  tags:
    - zabbix-server

- name: "RedHat | Use EPEL package name"
  set_fact:
    zabbix_server_package: "zabbix{{ zabbix_short_version }}-server-{{ zabbix_server_database }}"
  when:
    - zabbix_repo == "epel"
  tags:
    - zabbix-server

- name: "RedHat | Set some facts EPEL"
  set_fact:
    datafiles_path: "/usr/share/zabbix-{{ zabbix_server_database_long }}"
  when:
    - zabbix_repo == "epel"
  tags:
    - zabbix-server

- name: "RedHat | Set some facts Zabbix < 3.0"
  set_fact:
    datafiles_path: "/usr/share/doc/zabbix-server-{{ zabbix_server_database }}-{{ zabbix_version }}*"
  when:
    - zabbix_version is version('3.0', '<')
  tags:
    - zabbix-server

- name: "RedHat | Set facts for Zabbix >= 3.0"
  set_fact:
    datafiles_path: "/usr/share/doc/zabbix-server-{{ zabbix_server_database }}-{{ zabbix_version }}*"
  when:
    - zabbix_version is version('3.0', '>=')
  tags:
    - zabbix-server

- name: "RedHat | Install basic repo file"
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ zabbix_repo_yum }}"
  when:
    - zabbix_repo == "zabbix"
  tags:
    - zabbix-server

- name: "RedHat | Installing zabbix-server-{{ zabbix_server_database }}"
  yum:
    pkg: "{{ zabbix_server_package }}"
    state: "{{ zabbix_server_package_state }}"
  register: zabbix_server_package_installed
  until: zabbix_server_package_installed is succeeded
  tags:
    - zabbix-server

- name: "RedHat | Install Ansible module dependencies"
  yum:
    name: python-psycopg2
    state: present
  register: zabbix_server_dependencies_installed
  until: zabbix_server_dependencies_installed is succeeded
  when:
    - zabbix_database_creation
    - zabbix_server_database == 'pgsql'
    - ansible_distribution_major_version == "7" or ansible_distribution_major_version == "6"
  tags:
    - zabbix-server

- name: "RedHat | Install Ansible module dependencies on RHEL8"
  yum:
    name: python3-psycopg2
    state: present
  register: zabbix_server_dependencies_installed
  until: zabbix_server_dependencies_installed is succeeded
  when:
    - zabbix_database_creation
    - zabbix_server_database == 'pgsql'
    - ansible_distribution_major_version == "8"
  tags:
    - zabbix-server

- name: "RedHat | Install Mysql Client package RHEL7"
  yum:
    name:
      - mariadb
      - MySQL-python
    state: present
  register: zabbix_server_dependencies_installed
  until: zabbix_server_dependencies_installed is succeeded
  when:
    - zabbix_server_database == 'mysql'
    - ansible_distribution_major_version == "7"
  tags:
    - zabbix-server

- name: "RedHat | Install Mysql Client package RHEL5 - 6"
  yum:
    name:
      - mysql
      - MySQL-python
    state: present
  register: zabbix_server_dependencies_installed
  until: zabbix_server_dependencies_installed is succeeded
  when:
    - zabbix_server_database == 'mysql'
    - ansible_distribution_major_version == "6" or ansible_distribution_major_version == "5"
  tags:
    - zabbix-server

- name: "RedHat | Install PostgreSQL client package"
  yum:
    name: postgresql
    state: present
  register: zabbix_server_dependencies_installed
  until: zabbix_server_dependencies_installed is succeeded
  when:
    - zabbix_server_database == 'pgsql'
  tags:
    - zabbix-server

- name: "RedHat | Install related SELinux package"
  yum:
    name:
      - libsemanage-python
    state: present
  register: zabbix_server_dependencies_installed
  until: zabbix_server_dependencies_installed is succeeded
  when:
    - selinux_allow_zabbix_can_network
    - ansible_distribution_major_version == "7" or ansible_distribution_major_version == "6"
  tags:
    - zabbix-server

- name: "RedHat | Install related SELinux package on RHEL8"
  yum:
    name:
      - python3-libsemanage
    state: present
  register: zabbix_server_dependencies_installed
  until: zabbix_server_dependencies_installed is succeeded
  when:
    - selinux_allow_zabbix_can_network
    - ansible_distribution_major_version == "8"
  tags:
    - zabbix-server

- name: "RedHat | Enable httpd_can_connect_zabbix SELinux boolean"
  seboolean:
    name: httpd_can_connect_zabbix
    state: yes
    persistent: yes
  when:
    - selinux_allow_zabbix_can_http
  tags:
    - zabbix-server

- name: "RedHat | Enable zabbix_can_network SELinux boolean"
  seboolean:
    name: zabbix_can_network
    state: yes
    persistent: yes
  when:
    - selinux_allow_zabbix_can_network
  tags:
    - zabbix-server
