# Require the Azure provider plugin
require 'vagrant-azure'

# Create and configure the Azure VMs
Vagrant.configure('2') do |config|

  # Use dummy Azure box
  config.vm.box = 'azure-dummy'

  # Specify SSH key
  config.ssh.private_key_path = '~/.ssh/id_rsa'

  # Configure the Azure provider
  (1..3).each do |i|
    config.vm.define "srv#{i}" do |srv|
      srv.vm.provider 'azure' do |az|
        # Pull Azure AD service principal information from environment variables
        az.tenant_id = ENV['AZURE_TENANT_ID']
        az.client_id = ENV['AZURE_CLIENT_ID']
        az.client_secret = ENV['AZURE_CLIENT_SECRET']
        az.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']
        az.vm_image_urn = 'Canonical:UbuntuServer:18.04-LTS:latest'
        az.resource_group_name = 'LosCharros.com'
        az.location = 'francecentral'
        az.vm_name = "srv#{i}"
        az.vm_size = 'Standard_F1s'
        az.admin_username = "admin#{i}"
        az.vm_password = "admin#{i}pass"
      end
    end 
  end  
end 
