# Require the Azure provider plugin
require 'vagrant-azure'

# Create and configure the Azure VMs
Vagrant.configure('2') do |config|

  # Use dummy Azure box
  config.vm.box = 'azure-dummy'

  # Specify SSH key
  config.ssh.private_key_path = '~/.ssh/id_rsa'

  # Configure the Azure provider
  (1..3).each do |i|
    config.vm.define "srv#{i}" do |srv|
      srv.vm.provider 'azure' do |az|
        # Pull Azure AD service principal information from environment variables
        az.tenant_id = "38e72bba-3c22-4382-9323-ac1612931297"
        az.client_id = "http://azure-cli-2019-11-15-14-18-05"
        az.client_secret = "c6e76472-f14b-4d9f-bbfa-c5293777cd47"
        az.subscription_id = "2a36ea96-2890-4201-abfe-39dacf821363"
        az.vm_image_urn = 'Canonical:UbuntuServer:18.04-LTS:latest'
        az.resource_group_name = 'LosCharros.com'
        az.location = 'francecentral'
        az.vm_name = "srv#{i}"
        az.vm_size = 'Standard_F2s_v2'
        az.admin_username = "admin#{i}"
        az.vm_password = "admin#{i}pass"
      end
    end 
  end  
end 
