- name: main launch file
  hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo

  roles:

   - install_openldap
   - install_ftp
   - apache
     when: inventory_hostname in groups['srv-main']
   - postgresql
     when: inventory_hostname in groups['srv-main']
   - zabbix
     when: inventory_hostname in groups['srv-main']
   - zabbix-web
     when: inventory_hostname in groups['srv-main']
   - zabbix-agent
