- name: main launch file
  hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo

  roles:

#   - install_openldap
#   - include: install_ftp
   - apache
   - postgresql
   - zabbix
   - zabbix-web
   - zabbix-agent
