---
- name: main launch file
  hosts: srv-azure
  remote_user: vagrant
  become: yes
  become_method: sudo

  roles:

  - install_ftp    #- include: zabbix
  - install_openldap
#  - include: install_ftp
#  - zabbix
  - zabbix-web
